### PR TITLE
arkosupdate03262023

### PR DESCRIPTION
**Pull request by Slayer366**
Update SDL2 to v2.0.26.2
Update RetroArch to v1.15.0
Add Swanstation core for PSX
Update Mupen64Plus
Fix/Update GZDoom to reflect new SDL2-2.0.26.2
Update filebrowser CLI executable
Update Drastic and ScummVM launch scripts

### CODE REVIEW

**Comment by Slayer366** [comment]
Would you like to review this before merging?

**Comment by wummle** [comment]
if you are happy all is working happy for you to merge. Thankyou for your work on this

**Comment by Slayer366** [comment]
You're welcome, kind sir.  Thank you as well for your excellent contributions!
    On Tuesday, March 28, 2023 at 05:56:18 AM CDT, wummle ***@***.***> wrote:  
 
 


if you are happy all is working happy for you to merge. Thankyou for your work on this

**Comment by wummle** [comment]
Looks like the filebrowser is broken i dont use it so didnt spot it, getting This location can't be reached when trying to connect file a web browser any ideas? Paths looks right in settings 
image

**Comment by Slayer366** [comment]
I'll check it out.  I checked the binary from the terminal and all seemed okay, but perhaps it wasn't all sunshine and glory after all.  Could you share how you got to that screen?  That way I can check against it.  Worst comes to worst, we'll just put the original launcher back.

**Comment by wummle** [comment]
Connect to wifi then enable remote access from options then put the ip address into your web browser on your PC. could it be a permissions thing with the binary?

**Comment by Slayer366** [comment]
Yep.  Turns out the binary had some change that prevented access to the shares from the web browser.  Like you, I hadn't noticed since I always use MobaXterm to SSH into mine.  Replacing it with the original 'filebrowser' executable gets it working again.  How would you like for me to proceed, boss?

**Comment by wummle** [comment]
i am not the boss lol but if the new binary doesnt give us anything new maybe revert.

**Comment by Slayer366** [comment]
Alright.  Should be working again.

**Comment by wummle** [comment]
yep saw the git go live and tested working again thankyou for your help

**Pull request merged**
